/*
 * the API used to use the Map Authority map management server
 *
 * This is the public REST interface to the map management server
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Book struct {
	// Author is author of the book
	Author string `json:"author"`
	// ID is id of book
	Id string `json:"id"`
	// Price is the price of book
	Price float64 `json:"price"`
	// Title is title of book
	Title string `json:"title"`
}
